import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic';

const NextUIProvider = dynamic(() => import('@nextui-org/react').then(mod => mod.NextUIProvider), {
  ssr: false, // Disable server-side rendering for NextUIProvider.
});

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={inter.className}>
      <NextUIProvider>
        {children}
      </NextUIProvider>
    </div>
  )
}
